spring.application.name=ProductInvoice

server.port=8080

# Google Cloud SQL MySQL Connection
spring.datasource.url=jdbc:mysql:///dbproject?cloudSqlInstance=Product-Invoice:asia-south1:employee&socketFactory=com.google.cloud.sql.mysql.SocketFactory


spring.datasource.username=product
spring.datasource.password=Product@123
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Connection Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000